"""
Quiz Model - Daily Quizzes
===========================
Pydantic models for the quizzes collection.
Represents AI-generated quizzes based on chat history for gamification.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, List, Union
from datetime import datetime, date


class PyObjectId(str):
    """Custom ID type for Pydantic v2 models (DynamoDB compatible)."""
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema
        
        def validate(value, _info=None):
            if isinstance(value, str) and len(value) > 0:
                return value
            raise ValueError("Invalid ID - must be a non-empty string")
        
        return core_schema.with_info_plain_validator_function(
            validate,
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda x: str(x)
            )
        )


class QuizQuestion(BaseModel):
    """Individual quiz question with multiple choice options."""
    question_id: str  # Unique ID for the question (e.g., "q1", "q2")
    question_text: str = Field(..., min_length=5, max_length=500)
    options: List[str] = Field(..., min_length=2, max_length=4)
    correct_answer: str = Field(..., description="Must be one of the options")
    user_answer: Optional[str] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "question_id": "q1",
                "question_text": "What gas do plants release during photosynthesis?",
                "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
                "correct_answer": "Oxygen",
                "user_answer": None
            }
        }


class QuizCreate(BaseModel):
    """Schema for creating a quiz (generated by AI)."""
    profile_id: str
    topic: str = Field(..., min_length=3, max_length=100)
    source_conversation_ids: List[str] = Field(default_factory=list, description="Conversations used to generate quiz")
    questions: List[QuizQuestion] = Field(..., min_length=5, max_length=10)
    difficulty: str = Field(default="medium", pattern="^(easy|medium|hard)$")
    quiz_date: date = Field(default_factory=date.today, description="Date for which quiz was generated")
    
    class Config:
        json_schema_extra = {
            "example": {
                "profile_id": "507f1f77bcf86cd799439012",
                "topic": "Photosynthesis and Plant Biology",
                "source_conversation_ids": ["507f1f77bcf86cd799439013"],
                "questions": [
                    {
                        "question_id": "q1",
                        "question_text": "What gas do plants release?",
                        "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
                        "correct_answer": "Oxygen",
                        "user_answer": None
                    }
                ],
                "difficulty": "medium",
                "quiz_date": "2024-01-20"
            }
        }


class QuizInDB(BaseModel):
    """Quiz model as stored in MongoDB."""
    id: Optional[PyObjectId] = Field(default=None, alias="_id")
    profile_id: PyObjectId
    topic: str
    source_conversation_ids: List[PyObjectId] = Field(default_factory=list)
    questions: List[QuizQuestion]
    difficulty: str = Field(default="medium")
    quiz_date: date = Field(default_factory=date.today)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: str = Field(default="pending", pattern="^(pending|completed)$")
    score: Optional[int] = Field(default=None, ge=0, le=100)
    completed_at: Optional[datetime] = None
    xp_earned: Optional[int] = Field(default=None, ge=0)
    is_backlog: bool = Field(default=False, description="Whether this is a backlog quiz (missed day)")
    
    @field_validator('quiz_date', mode='before')
    @classmethod
    def convert_datetime_to_date(cls, v):
        """Convert datetime from MongoDB to date."""
        if isinstance(v, datetime):
            return v.date()
        return v
    
    class Config:
        populate_by_name = True
        from_attributes = True
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            date: lambda v: v.isoformat()
        }
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439014",
                "profile_id": "507f1f77bcf86cd799439012",
                "topic": "Photosynthesis and Plant Biology",
                "source_conversation_ids": ["507f1f77bcf86cd799439013"],
                "questions": [],
                "difficulty": "medium",
                "quiz_date": "2024-01-20",
                "created_at": "2024-01-20T10:00:00",
                "status": "pending",
                "score": None,
                "completed_at": None,
                "xp_earned": None
            }
        }


class QuizResponse(BaseModel):
    """Quiz response model (without answers for active quizzes)."""
    id: str = Field(..., alias="_id")
    profile_id: str
    topic: str
    difficulty: str
    quiz_date: date
    created_at: datetime
    status: str
    score: Optional[int] = None
    completed_at: Optional[datetime] = None
    xp_earned: Optional[int] = None
    total_questions: int
    is_backlog: bool = False
    
    class Config:
        populate_by_name = True
        json_schema_extra = {
            "example": {
                "_id": "507f1f77bcf86cd799439014",
                "profile_id": "507f1f77bcf86cd799439012",
                "topic": "Photosynthesis",
                "difficulty": "medium",
                "quiz_date": "2024-01-20",
                "created_at": "2024-01-20T10:00:00",
                "status": "pending",
                "score": None,
                "completed_at": None,
                "xp_earned": None,
                "total_questions": 5,
                "is_backlog": False
            }
        }


class QuizQuestionsResponse(BaseModel):
    """Quiz with questions (for taking quiz - without correct answers)."""
    id: str = Field(..., alias="_id")
    profile_id: str
    topic: str
    difficulty: str
    quiz_date: date
    questions: List[dict]  # Questions without correct_answer field
    total_questions: int
    
    class Config:
        populate_by_name = True


class QuizSubmission(BaseModel):
    """Schema for submitting quiz answers."""
    answers: dict = Field(..., description="Dictionary mapping question_id to user's selected answer")
    
    class Config:
        json_schema_extra = {
            "example": {
                "answers": {
                    "q1": "Oxygen",
                    "q2": "Energy ke liye",
                    "q3": "Chlorophyll"
                }
            }
        }


class QuizSubmissionResponse(BaseModel):
    """Response after submitting quiz with results."""
    quiz_id: str
    score: int = Field(..., ge=0, le=100)
    correct_count: int
    total_questions: int
    xp_earned: int
    current_xp: int
    streak_days: int
    streak_maintained: bool
    is_backlog: bool = False
    feedback: List[dict] = Field(..., description="Per-question feedback")
    
    class Config:
        json_schema_extra = {
            "example": {
                "quiz_id": "507f1f77bcf86cd799439014",
                "score": 80,
                "correct_count": 4,
                "total_questions": 5,
                "xp_earned": 40,
                "current_xp": 1540,
                "streak_days": 4,
                "streak_maintained": True,
                "is_backlog": False,
                "feedback": [
                    {
                        "question_id": "q1",
                        "correct": True,
                        "user_answer": "Oxygen",
                        "correct_answer": "Oxygen"
                    }
                ]
            }
        }


class QuizRevisionQuestion(BaseModel):
    """Question model for revision with full details including user's answer."""
    question_id: str
    question_text: str
    options: List[str]
    correct_answer: str
    user_answer: Optional[str] = None
    is_correct: bool = False


class QuizRevisionResponse(BaseModel):
    """Quiz model for revision with all question details."""
    id: str = Field(..., alias="_id")
    profile_id: str
    topic: str
    difficulty: str
    quiz_date: date
    created_at: datetime
    completed_at: Optional[datetime] = None
    score: int
    xp_earned: int
    questions: List[QuizRevisionQuestion]
    total_questions: int
    correct_count: int
    is_backlog: bool = False
    
    class Config:
        populate_by_name = True


class SyncQuizResponse(BaseModel):
    """Quiz model for sync response with all data."""
    id: str = Field(..., alias="_id")
    profile_id: str
    topic: str
    difficulty: str
    quiz_date: date
    created_at: datetime
    status: str
    score: Optional[int] = None
    completed_at: Optional[datetime] = None
    xp_earned: Optional[int] = None
    questions: List[QuizQuestion] = Field(default_factory=list)
    is_backlog: bool = False
    
    class Config:
        populate_by_name = True


# ============================================
# Quiz Summary & Learning Insights Models
# ============================================

class ConceptExplanation(BaseModel):
    """A concept explanation generated by the LLM."""
    concept: str
    explanation: str
    explanation_hindi: Optional[str] = None


class QuizSummaryResponse(BaseModel):
    """Response model for immediate quiz summary after completion."""
    quiz_id: str
    topic: str
    score: int = Field(..., ge=0, le=100)
    correct_count: int
    total_questions: int
    performance_level: str = Field(..., description="excellent|good|needs_improvement|poor")
    summary_text: str
    summary_text_hindi: Optional[str] = None
    topics_to_review: List[str] = Field(default_factory=list)
    encouragement: str
    encouragement_hindi: Optional[str] = None
    study_tips: List[str] = Field(default_factory=list)
    concepts_explained: List[ConceptExplanation] = Field(default_factory=list)
    next_steps: str
    generated_at: datetime
    
    class Config:
        json_schema_extra = {
            "example": {
                "quiz_id": "507f1f77bcf86cd799439014",
                "topic": "Photosynthesis",
                "score": 60,
                "correct_count": 3,
                "total_questions": 5,
                "performance_level": "needs_improvement",
                "summary_text": "You showed understanding of basic concepts but need more practice.",
                "summary_text_hindi": "आपने बुनियादी अवधारणाओं की समझ दिखाई लेकिन अभ्यास की ज़रूरत है।",
                "topics_to_review": ["Chloroplast function", "Light reactions"],
                "encouragement": "Keep practicing! You're making progress.",
                "encouragement_hindi": "अभ्यास करते रहो! आप प्रगति कर रहे हो।",
                "study_tips": ["Review the process of photosynthesis step by step"],
                "concepts_explained": [
                    {
                        "concept": "Chloroplast",
                        "explanation": "Chloroplasts are where photosynthesis happens in plant cells.",
                        "explanation_hindi": "क्लोरोप्लास्ट वह जगह है जहां पौधों की कोशिकाओं में प्रकाश संश्लेषण होता है।"
                    }
                ],
                "next_steps": "Focus on understanding the light reactions of photosynthesis.",
                "generated_at": "2024-01-20T14:30:00"
            }
        }


class SubjectInsight(BaseModel):
    """Subject-wise learning insight."""
    subject: str
    status: str = Field(..., description="strong|average|weak")
    score_average: float = Field(..., ge=0, le=100)
    improvement_areas: List[str] = Field(default_factory=list)
    recommendation: str
    recommendation_hindi: Optional[str] = None


class WeakTopicExplanation(BaseModel):
    """Detailed explanation for a weak topic."""
    topic: str
    subject: str
    why_important: str
    simple_explanation: str
    simple_explanation_hindi: Optional[str] = None
    practice_tip: str


class StrengthArea(BaseModel):
    """Recognition of student's strength area."""
    area: str
    praise: str
    praise_hindi: Optional[str] = None


class WeeklyGoal(BaseModel):
    """Weekly learning goal recommendation."""
    goal: str
    goal_hindi: Optional[str] = None
    subject: str


class OverallAssessment(BaseModel):
    """Overall performance assessment."""
    level: str = Field(..., description="excellent|good|average|needs_improvement")
    summary: str
    summary_hindi: Optional[str] = None


class LearningInsightsResponse(BaseModel):
    """Comprehensive learning insights for the student profile page."""
    has_data: bool = True
    message: Optional[str] = None  # Message when no data available
    message_hindi: Optional[str] = None
    
    # Profile info
    profile_name: Optional[str] = None
    grade_level: Optional[str] = None
    
    # Statistics
    total_quizzes: int = 0
    overall_average: float = 0
    performance_trend: str = Field(default="neutral", description="improving|neutral|declining")
    analysis_period_days: int = 30
    
    # AI-Generated Insights
    overall_assessment: Optional[OverallAssessment] = None
    subject_insights: List[SubjectInsight] = Field(default_factory=list)
    weak_topics_explanation: List[WeakTopicExplanation] = Field(default_factory=list)
    strengths: List[StrengthArea] = Field(default_factory=list)
    weekly_goals: List[WeeklyGoal] = Field(default_factory=list)
    
    # Motivational message
    motivational_message: Optional[str] = None
    motivational_message_hindi: Optional[str] = None
    
    generated_at: Optional[datetime] = None
    
    class Config:
        json_schema_extra = {
            "example": {
                "has_data": True,
                "profile_name": "Rahul",
                "grade_level": "6th",
                "total_quizzes": 15,
                "overall_average": 72.5,
                "performance_trend": "improving",
                "analysis_period_days": 30,
                "overall_assessment": {
                    "level": "good",
                    "summary": "You're making good progress across subjects!",
                    "summary_hindi": "आप विषयों में अच्छी प्रगति कर रहे हो!"
                },
                "subject_insights": [
                    {
                        "subject": "Mathematics",
                        "status": "strong",
                        "score_average": 85,
                        "improvement_areas": ["Word problems"],
                        "recommendation": "Challenge yourself with harder problems.",
                        "recommendation_hindi": "कठिन प्रश्नों से खुद को चुनौती दो।"
                    }
                ],
                "weak_topics_explanation": [
                    {
                        "topic": "Fractions",
                        "subject": "Mathematics",
                        "why_important": "Fractions are used in many real-life situations.",
                        "simple_explanation": "A fraction shows parts of a whole.",
                        "simple_explanation_hindi": "भिन्न एक पूर्ण के भागों को दर्शाता है।",
                        "practice_tip": "Practice dividing shapes into equal parts."
                    }
                ],
                "strengths": [
                    {
                        "area": "Science concepts",
                        "praise": "You understand scientific concepts very well!",
                        "praise_hindi": "आप वैज्ञानिक अवधारणाओं को बहुत अच्छी तरह समझते हो!"
                    }
                ],
                "weekly_goals": [
                    {
                        "goal": "Complete 3 math quizzes focusing on fractions",
                        "goal_hindi": "भिन्न पर ध्यान केंद्रित करते हुए 3 गणित क्विज़ पूरा करें",
                        "subject": "Mathematics"
                    }
                ],
                "motivational_message": "You're doing great! Keep up the good work.",
                "motivational_message_hindi": "आप बहुत अच्छा कर रहे हो! अच्छा काम जारी रखो।",
                "generated_at": "2024-01-20T14:30:00"
            }
        }

